# Generated by Django 4.2 on 2024-01-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partypes', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField()),
                ('blurb', models.CharField()),
                ('classes', models.ManyToManyField(blank=True, to='classes.class')),
                ('partype_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partypes.partype')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('champion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champions.champion')),
            ],
        ),
    ]
